name: build
on:
    - push
    - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby
        with:
          ruby-version: '2.3.0'
          bundler-cache: true
      - name: Install dependences
        run: bundle install
      - name: Create build
        run: bundle exec build
      - name: Run Specs
        run: bundle exec spec
