name: build
on:
    - push
    - pull_request
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.3.0', '2.7', '3.1', 'jruby-9.1', 'jruby-9.2', 'jruby-9.3', 'jruby-head']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Create build
        run: bundle exec build

      - name: Run Specs
        run: bundle exec spec
