name: build
on:
    - push
    - pull_request
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.1', '2.2', '2.3', '2.4', '2.5', '2.6', '2.7', 'jruby-9.1.17', 'jruby-9.2.21']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: 1.17.3
          bundler-cache: true

      - name: Create build
        run: bundle exec rake build

      - name: Run Specs
        run: bundle exec rake spec
